# Generated by Django 5.0.7 on 2024-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=90)),
                ('middle_initial', models.CharField(max_length=5)),
                ('last_name', models.CharField(max_length=90)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
