# Generated by Django 4.2.6 on 2024-07-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address_student_birthday_student_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_at',
            new_name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='performance',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
