# Generated by Django 5.0.7 on 2025-01-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_options_alter_studentschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='performance',
            field=models.CharField(default='Not set', max_length=45),
        ),
    ]
