# Generated by Django 5.0.7 on 2025-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_performance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='studentschedule',
            table='student_scheds',
        ),
    ]
