# Generated by Django 4.2.6 on 2024-07-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=200)),
                ('code', models.CharField(default=None, max_length=45)),
                ('building_name', models.CharField(default=None, max_length=200)),
                ('status', models.CharField(default='Available', max_length=45)),
            ],
        ),
    ]
