# Generated by Django 4.2.6 on 2024-07-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='building_name',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default=None, max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
