# Generated by Django 4.2.6 on 2024-07-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_alter_classroom_building_name_alter_classroom_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='building_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
