# Generated by Django 4.2.6 on 2024-07-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_alter_classroom_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
