# Generated by Django 5.0.7 on 2025-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
